# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('travelto', models.DateField()),
                ('travelfrom', models.DateField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='users.User')),
                ('travellers', models.ManyToManyField(related_name='travellers', to='users.User')),
            ],
        ),
    ]
